apiVersion: policies.kyverno.io/v1alpha1
kind: MutatingPolicy
metadata:
  name: add-instance-pool-nodeselector
  annotations:
    policies.kyverno.io/title: Add nodeSelector based on the Instance Pool annotation on the namespace
    policies.kyverno.io/category: Platform
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.15.0
    policies.kyverno.io/description: The nodeSelector field uses labels to select the node on which a Pod can be scheduled. This can be useful when Pods have specific needs that only certain nodes in a cluster can provide. This policy adds the nodeSelector field to a Pod spec and configures it with labels based on the namespace annotations.
spec:
  evaluation:
    mutateExisting:
      enabled: true

  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
          - daemonsets
          - statefulsets
      - apiGroups:
          - batch
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - jobs
          - cronjobs

  variables:
    - name: instancePool
      expression: >
        (has(resource.Get("v1", "namespaces", "", object.metadata.namespace).metadata.annotations) &&
         "tractor.scout.ch/instance-pool" in resource.Get("v1", "namespaces", "", object.metadata.namespace).metadata.annotations)
        ?
        resource.Get("v1", "namespaces", "", object.metadata.namespace).metadata.annotations["tractor.scout.ch/instance-pool"]
        :
        null

  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: |
          variables.instancePool == null ?
          []
          :
          (
            !has(object.spec.nodeSelector) ?
            [
              JSONPatch{
                op: "add",
                path: "/spec/nodeSelector",
                value: dyn({
                  "kaas.infomaniak.cloud/instance-pool": variables.instancePool
                })
              }
            ]
            :
            [
              JSONPatch{
                op: "add",
                path: "/spec/nodeSelector/kaas.infomaniak.cloud~1instance-pool",
                value: variables.instancePool
              }
            ]
          )

    - patchType: JSONPatch
      jsonPatch:
        expression: |
          variables.instancePool == null || !has(object.spec.template) ?
          []
          :
          (
            !has(object.spec.template.spec.nodeSelector) ?
            [
              JSONPatch{
                op: "add",
                path: "/spec/template/spec/nodeSelector",
                value: dyn({
                  "kaas.infomaniak.cloud/instance-pool": variables.instancePool
                })
              }
            ]
            :
            [
              JSONPatch{
                op: "add",
                path: "/spec/template/spec/nodeSelector/kaas.infomaniak.cloud~1instance-pool",
                value: variables.instancePool
              }
            ]
          )

    - patchType: JSONPatch
      jsonPatch:
        expression: |
          variables.instancePool == null || !has(object.spec.jobTemplate) ?
          []
          :
          (
            !has(object.spec.jobTemplate.spec.template.spec.nodeSelector) ?
            [
              JSONPatch{
                op: "add",
                path: "/spec/jobTemplate/spec/template/spec/nodeSelector",
                value: dyn({
                  "kaas.infomaniak.cloud/instance-pool": variables.instancePool
                })
              }
            ]
            :
            [
              JSONPatch{
                op: "add",
                path: "/spec/jobTemplate/spec/template/spec/nodeSelector/kaas.infomaniak.cloud~1instance-pool",
                value: variables.instancePool
              }
            ]
          )
