---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: infomaniak
  namespace: velero
spec:
  accessMode: ReadWrite
  default: true
  objectStorage:
    bucket: k8s-backups
  config:
    cloud: infomaniak
  provider: community.openstack.org/openstack
