---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: infomaniak
  namespace: velero
spec:
  accessMode: ReadWrite
  default: true
  config:
    region: "us-east-1"
    s3ForcePathStyle: "true"
    checksumAlgorithm: ""
    tagging: ""
  provider: velero.io/aws
  credential:
    key: tractor-k8s-backup
    name: infomaniak-s3-credentials
