on:
  pull_request:

name: Check Pull Request

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: tofu
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2
        with:
          tofu_version: 1.10.7

      - name: OpenTofu Format
        id: fmt
        run: tofu fmt -check -recursive -diff

      - name: Generate Comment
        if: success() || failure()
        shell: bash
        run: |
          cat <<EOF>> pretty_lint_result.txt
          #### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*
          EOF

      - name: Annotate PR
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987 # v3
        if: success() || failure()
        with:
          header: lint
          path: tofu/pretty_lint_result.txt

      - name: Annotate Run
        if: success() || failure()
        shell: bash
        run: cat pretty_lint_result.txt >> $GITHUB_STEP_SUMMARY

  plan:
    name: "Prepare Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tofu
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Plan
        id: plan
        uses: ./.github/actions/common-plan
        with:
          lock: "false"
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          INFOMANIAK_TOKEN: ${{ secrets.INFOMANIAK_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

      - name: Annotate PR
        uses: marocchino/sticky-pull-request-comment@70d2764d1a7d5d9560b100cbea0077fc8f633987 # v3
        if: success() || failure()
        with:
          header: plan
          path: tofu/pretty_plan_short.txt

      - name: Annotate Run
        if: success() || failure()
        shell: bash
        run: cat pretty_plan.txt >> $GITHUB_STEP_SUMMARY
