on:
  pull_request:

name: Check Pull Request

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: tofu
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2
        with:
          tofu_version: 1.11.6

      - name: OpenTofu Format
        id: fmt
        run: tofu fmt -check -recursive -diff

      - name: Generate Comment
        if: success() || failure()
        shell: bash
        run: |
          cat <<EOF>> pretty_lint_result.txt
          #### OpenTofu Format and Style 🖌\`${{ steps.fmt.outcome }}\`

          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*
          EOF

      - name: Annotate PR
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        if: success() || failure()
        with:
          header: lint
          path: tofu/pretty_lint_result.txt

      - name: Annotate Run
        if: success() || failure()
        shell: bash
        run: cat pretty_lint_result.txt >> $GITHUB_STEP_SUMMARY

  plan:
    name: "Prepare Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tofu
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          client-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Plan
        id: plan
        uses: ./.github/actions/common-plan
        with:
          lock: "false"
        env:
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
          INFOMANIAK_TOKEN: ${{ secrets.INFOMANIAK_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
          OS_APPLICATION_CREDENTIAL_NAME: ${{ secrets.OS_APPLICATION_CREDENTIAL_NAME }}
          OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}

      - name: Annotate PR
        uses: marocchino/sticky-pull-request-comment@5770ad5eb8f42dd2c4f34da00c94c5381e49af88 # v3.0.5
        if: success() || failure()
        with:
          header: plan
          path: tofu/pretty_plan_short.txt

      - name: Annotate Run
        if: success() || failure()
        shell: bash
        run: cat pretty_plan.txt >> $GITHUB_STEP_SUMMARY
